### ISSUE TITLE
请问产品是否支持拓展操作栏？

### ISSUE THREAD

**Issue by TJX666666** [tcplayer/tcplayer-demo#4]
我想在这个里面再加入一个评论组件 
![image](https://user-images.githubusercontent.com/51389459/226276044-23223377-c98a-497d-8159-9c89f3db8e99.png)

**Comment by vincentism** [comment]
这个要自己实现了，播放器没有现成的这样的接口。在播放器ready之后，在页面上添加dom节点和业务逻辑就可以了。移动端这个区域可能不够宽，可以把评论区域放到画面之外

**Comment by TJX666666** [comment]
> 这个要自己实现了，播放器没有现成的这样的接口。在播放器ready之后，在页面上添加dom节点和业务逻辑就可以了。移动端这个区域可能不够宽，可以把评论区域放到画面之外
```
var el = Button.prototype.createEl.call(this);
el.appendChild(TCPlayer.dom.createEl('div',{})
```
如果使用这样的方式 append到节点上 但是没办法定位到底部的操作栏呀？ 对象是controlBar吗？

以下代码并不生效
```
 player.on('ready', function (event) {
    console.info('loadeddata', event);
    var controlBar = TCPlayer.getComponent('controlBar');
    console.log(controlBar)
    var el = controlBar.prototype.createEl.call(this);
    let _html = '<div>123123</div>';
    el.appendChild(TCPlayer.dom.createEl('div', {
      className: 'self-init',
      innerHTML: _html,
    }));
  });
```

**Comment by vincentism** [comment]
如果要用拓展组件的方式，要在播放器实例化之前才有效

**Comment by TJX666666** [comment]
> 如果要用拓展组件的方式，要在播放器实例化之前才有效

采用了无UI方式 自定义了操作栏 但是发现点击video内部不触发点击事件 无法处理自定义操作栏的显示与隐藏

**Comment by Guocheng-c** [comment]
> > 如果要用拓展组件的方式，要在播放器实例化之前才有效
> 
> 采用了无UI方式 自定义了操作栏 但是发现点击video内部不触发点击事件 无法处理自定义操作栏的显示与隐藏

请问最后怎么实现的
